email-project/force-app/main/default/objects/email_log__x/email_log__x.object-meta.xml
<CustomObject>
    <description>email_log</description>
    <externalDataSource>email_api</externalDataSource>
    <externalName>email_log</externalName>
    <label>email_log</label>
    <pluralLabel>email_log</pluralLabel>
</CustomObject>

email-project/force-app/main/default/objects/email_log__x/fields/customer_id__c.field-meta.xml
<CustomField>
    <fullName>customer_id__c</fullName>
    <description>customer_id</description>
    <externalDeveloperName>customer_id</externalDeveloperName>
    <label>customer_id</label>
    <length>255</length>
    <referenceTargetField>Account.GradwellId__c</referenceTargetField>
    <referenceTo>Account</referenceTo>
    <relationshipName>customer_id</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

old/objects/email_log__x/fields/email_to__c.field-meta.xml
<CustomField>
    <fullName>email_to__c</fullName>
    <description>email_to</description>
    <externalDeveloperName>email_to</externalDeveloperName>
    <label>email_to</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

old/objects/email_log__x/fields/latest_event__c.field-meta.xml
<CustomField>
    <fullName>latest_event__c</fullName>
    <description>latest_event</description>
    <externalDeveloperName>latest_event</externalDeveloperName>
    <label>latest_event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

old/objects/email_log__x/fields/sent_ts__c.field-meta.xml
<CustomField>
    <fullName>sent_ts__c</fullName>
    <description>sent_ts</description>
    <externalDeveloperName>sent_ts</externalDeveloperName>
    <label>sent_ts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-project/force-app/main/default/objects/email_log__x/fields/subject__c.field-meta.xml
<CustomField>
    <fullName>subject__c</fullName>
    <description>subject</description>
    <externalDeveloperName>subject</externalDeveloperName>
    <label>subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-project/force-app/main/default/objects/events__x/events__x.object-meta.xml
<CustomObject>
    <description>events</description>
    <externalDataSource>email_api</externalDataSource>
    <externalName>events</externalName>
    <label>events</label>
    <pluralLabel>events</pluralLabel>
</CustomObject>

email-project/force-app/main/default/objects/events__x/fields/event__c.field-meta.xml
<CustomField>
    <fullName>event__c</fullName>
    <description>event</description>
    <externalDeveloperName>event</externalDeveloperName>
    <label>event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

email-project/force-app/main/default/objects/events__x/fields/event_ts__c.field-meta.xml
<CustomField>
    <fullName>event_ts__c</fullName>
    <description>event_ts</description>
    <externalDeveloperName>event_ts</externalDeveloperName>
    <label>event_ts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

old/objects/events__x/fields/message_id__c.field-meta.xml
<CustomField>
    <fullName>message_id__c</fullName>
    <description>message_id</description>
    <externalDeveloperName>message_id</externalDeveloperName>
    <label>message_id</label>
    <length>255</length>
    <referenceTo>email_log__x</referenceTo>
    <relationshipName>message_id</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

email-project/force-app/main/default/classes/EmailController.cls
public with sharing class EmailController {

    @AuraEnabled(Cacheable=true)
    public static List<email_log__x> getEmails(Id customer_id){
      //get the gradwell id for the account and use it to get the emails

      return [SELECT ExternalId, email_to__c, latest_event__c, subject__c FROM email_log__x WHERE customer_id__c =:customer_id];
    }

    @AuraEnabled(Cacheable=true)
    public static List<email_log__x> getAllEmails(){
      return [SELECT ExternalId, email_to__c, latest_event__c, subject__c, sent_ts__c FROM email_log__x];
    }

    @AuraEnabled(Cacheable=true)
    public static List<events__x> getAllEvents() {
      return [SELECT ExternalId, event__c, event_ts__c, message_id__c FROM events__x];
    }
}